FROM debian:stable

###
# install dependencies
RUN apt update && apt install --no-install-recommends --assume-yes \
    locales \
    gettext \
    man-db \
    psmisc \
    procps \
    nano \
    tree \
    ncal \
    x11-apps \
    python3 \
    python-is-python3 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

###
# install locales and set default
RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
RUN sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen
RUN sed -i 's/^# *\(it_IT.UTF-8\)/\1/' /etc/locale.gen
RUN locale-gen
RUN update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

###
# set user and group
ARG user=gsh-user
ARG group=gsh-user
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/sh -m ${user} # <--- the '-m' create a user home directory

###
# switch to user
USER ${uid}:${gid}
WORKDIR /home/${user}


### use the local customized version (GameShell-Browser with custom missions)
### (generated by ./utils/gameshell_archive.sh -at -N "gameshell")
COPY --chown=gsh-user:gsh-user gameshell.sh .

### entrypoint wrapper -- conditionally hides python (GSH_ENABLE_PYTHON=0,
### set per-session by deploy/gsh-session.sh) before handing off to the game
COPY --chown=gsh-user:gsh-user deploy/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
